import { Container } from "nhsuk-react-components";
import { PageHeader } from "@/components/ui/PageHeader";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Conditions",
};

export default function TermsPage() {
  return (
    <Container>
      <PageHeader title="Terms and Conditions" />
      <div className="nhsuk-reading-width">
        <p>
          By accessing this portfolio prototype, you agree that you understand it is a demonstration
          system. It is not intended for clinical use, diagnostics, or any real-world health
          applications.
        </p>
        <h2>Disclaimer</h2>
        <p>
          The information and data displayed herein are generated by synthetic algorithms. Any
          resemblance to real persons, living or dead, is purely coincidental.
        </p>
      </div>
    </Container>
  );
}
