"""initial schema

Revision ID: 9cc94d097e1a
Revises: 
Create Date: 2026-09-25 22:09:01.852726

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '9cc94d097e1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject')
    )
    op.create_table('audit_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('actor_role', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=True),
    sa.Column('resource_id', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=False),
    sa.Column('ip_hash', sa.Text(), nullable=True),
    sa.Column('prev_hash', sa.Text(), nullable=False),
    sa.Column('event_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dq_ruleset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rule_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('dq_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ruleset_version', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.Text(), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingestion_bundle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Text(), nullable=False),
    sa.Column('bundle_type', sa.Text(), nullable=False),
    sa.Column('resource_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('operation_outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dq_rule',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('ruleset_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('fhirpath', sa.Text(), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ruleset_id'], ['dq_ruleset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dq_rule_ruleset_id'), 'dq_rule', ['ruleset_id'], unique=False)
    op.create_table('fhir_resource',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('logical_id', sa.Text(), nullable=False),
    sa.Column('version_id', sa.Text(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_bundle', sa.Uuid(), nullable=True),
    sa.Column('security_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_bundle'], ['ingestion_bundle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'logical_id', 'version_id')
    )
    op.create_index(op.f('ix_fhir_resource_logical_id'), 'fhir_resource', ['logical_id'], unique=False)
    op.create_index(op.f('ix_fhir_resource_resource_type'), 'fhir_resource', ['resource_type'], unique=False)
    op.create_table('patient',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('logical_id', sa.Text(), nullable=False),
    sa.Column('nhs_number', sa.Text(), nullable=True),
    sa.Column('nhs_number_status', sa.Text(), nullable=True),
    sa.Column('family_name', sa.Text(), nullable=True),
    sa.Column('given_names', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('deceased', sa.Boolean(), nullable=False),
    sa.Column('postcode', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['fhir_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_patient_logical_id'), 'patient', ['logical_id'], unique=True)
    op.create_index(op.f('ix_patient_nhs_number'), 'patient', ['nhs_number'], unique=False)
    op.create_table('condition',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('logical_id', sa.Text(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('code_system', sa.Text(), nullable=False),
    sa.Column('code_value', sa.Text(), nullable=False),
    sa.Column('code_display', sa.Text(), nullable=True),
    sa.Column('clinical_status', sa.Text(), nullable=True),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('abatement_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.resource_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['fhir_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_condition_logical_id'), 'condition', ['logical_id'], unique=True)
    op.create_index(op.f('ix_condition_patient_id'), 'condition', ['patient_id'], unique=False)
    op.create_table('dq_finding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('resource_logical_id', sa.Text(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.resource_id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['fhir_resource.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['dq_rule.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['dq_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dq_finding_rule_id'), 'dq_finding', ['rule_id'], unique=False)
    op.create_index(op.f('ix_dq_finding_run_id'), 'dq_finding', ['run_id'], unique=False)
    op.create_table('encounter',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('logical_id', sa.Text(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('class', sa.Text(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admission_source', sa.Text(), nullable=True),
    sa.Column('discharge_disposition', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.resource_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['fhir_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_encounter_logical_id'), 'encounter', ['logical_id'], unique=True)
    op.create_index(op.f('ix_encounter_patient_id'), 'encounter', ['patient_id'], unique=False)
    op.create_table('medication_request',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('logical_id', sa.Text(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('dm_d_code', sa.Text(), nullable=True),
    sa.Column('dm_d_display', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('authored_on', sa.Date(), nullable=True),
    sa.Column('dosage_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.resource_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['fhir_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_medication_request_logical_id'), 'medication_request', ['logical_id'], unique=True)
    op.create_index(op.f('ix_medication_request_patient_id'), 'medication_request', ['patient_id'], unique=False)
    op.create_table('observation',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('logical_id', sa.Text(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('code_system', sa.Text(), nullable=False),
    sa.Column('code_value', sa.Text(), nullable=False),
    sa.Column('code_display', sa.Text(), nullable=True),
    sa.Column('value_quantity', sa.Numeric(), nullable=True),
    sa.Column('value_unit', sa.Text(), nullable=True),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounter.resource_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.resource_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['fhir_resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_observation_logical_id'), 'observation', ['logical_id'], unique=True)
    op.create_index(op.f('ix_observation_patient_id'), 'observation', ['patient_id'], unique=False)
    op.create_table('review_task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to', sa.Text(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_ms', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['dq_finding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_task_finding_id'), 'review_task', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_task_finding_id'), table_name='review_task')
    op.drop_table('review_task')
    op.drop_index(op.f('ix_observation_patient_id'), table_name='observation')
    op.drop_index(op.f('ix_observation_logical_id'), table_name='observation')
    op.drop_table('observation')
    op.drop_index(op.f('ix_medication_request_patient_id'), table_name='medication_request')
    op.drop_index(op.f('ix_medication_request_logical_id'), table_name='medication_request')
    op.drop_table('medication_request')
    op.drop_index(op.f('ix_encounter_patient_id'), table_name='encounter')
    op.drop_index(op.f('ix_encounter_logical_id'), table_name='encounter')
    op.drop_table('encounter')
    op.drop_index(op.f('ix_dq_finding_run_id'), table_name='dq_finding')
    op.drop_index(op.f('ix_dq_finding_rule_id'), table_name='dq_finding')
    op.drop_table('dq_finding')
    op.drop_index(op.f('ix_condition_patient_id'), table_name='condition')
    op.drop_index(op.f('ix_condition_logical_id'), table_name='condition')
    op.drop_table('condition')
    op.drop_index(op.f('ix_patient_nhs_number'), table_name='patient')
    op.drop_index(op.f('ix_patient_logical_id'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_fhir_resource_resource_type'), table_name='fhir_resource')
    op.drop_index(op.f('ix_fhir_resource_logical_id'), table_name='fhir_resource')
    op.drop_table('fhir_resource')
    op.drop_index(op.f('ix_dq_rule_ruleset_id'), table_name='dq_rule')
    op.drop_table('dq_rule')
    op.drop_table('ingestion_bundle')
    op.drop_table('dq_run')
    op.drop_table('dq_ruleset')
    op.drop_table('audit_event')
    op.drop_table('app_user')
    # ### end Alembic commands ###
